"""create_initial_tables

Revision ID: 7cb9dec5e088
Revises: 
Create Date: 2026-02-08 13:13:06.328924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb9dec5e088'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref_mouthpieces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('variant', sa.String(), nullable=True),
    sa.Column('material', sa.Enum('HR', 'METAL', 'PLASTIC', 'WOOD', name='materialtype'), nullable=False),
    sa.Column('baffle_type', sa.Enum('STRAIGHT', 'ROLLOVER', 'STEP', 'CONCAVE', name='baffletype'), nullable=False),
    sa.Column('chamber_size', sa.Enum('SMALL', 'MEDIUM', 'MEDIUM_LARGE', 'LARGE', name='chambersize'), nullable=False),
    sa.Column('manufacturing_method', sa.Enum('CNC', 'HAND_FINISHED', 'CAST', name='mfgmethod'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ref_reeds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('cut', sa.Enum('FILED', 'UNFILED', name='cuttype'), nullable=False),
    sa.Column('material', sa.Enum('CANE', 'SYNTHETIC', 'COATED', name='reedmaterial'), nullable=False),
    sa.Column('strength_label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ref_tip_openings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mouthpiece_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('opening_inch', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('facing_length', sa.Enum('SHORT', 'MEDIUM', 'LONG', name='facinglength'), nullable=False),
    sa.ForeignKeyConstraint(['mouthpiece_id'], ['ref_mouthpieces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('instrument', sa.Enum('SOPRANINO', 'SOPRANO', 'ALTO', 'TENOR', 'BARITONE', 'BASS', 'CONTRABASS', name='instrumenttype'), nullable=False),
    sa.Column('genre', sa.Enum('JAZZ', 'CLASSICAL', 'POP', 'FUNK', 'OTHER', name='genre'), nullable=False),
    sa.Column('sub_genre', sa.String(), nullable=True),
    sa.Column('skill_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ENTHUSIAST', 'SEMI_PRO', 'PRO', name='skilllevel'), nullable=False),
    sa.Column('player_hours', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH', name='playerhours'), nullable=False),
    sa.Column('mouthpiece_id', sa.Uuid(), nullable=False),
    sa.Column('tip_opening_id', sa.Uuid(), nullable=False),
    sa.Column('reed_id', sa.Uuid(), nullable=False),
    sa.Column('suitability_rating', sa.Integer(), nullable=False),
    sa.Column('resistance_feel', sa.Integer(), nullable=False),
    sa.Column('brightness_feel', sa.Integer(), nullable=False),
    sa.Column('min_dynamic', sa.Integer(), nullable=False),
    sa.Column('max_dynamic', sa.Integer(), nullable=False),
    sa.Column('strength_rating', sa.Integer(), nullable=False),
    sa.Column('modifications', sa.Boolean(), nullable=True),
    sa.Column('modification_details', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['mouthpiece_id'], ['ref_mouthpieces.id'], ),
    sa.ForeignKeyConstraint(['reed_id'], ['ref_reeds.id'], ),
    sa.ForeignKeyConstraint(['tip_opening_id'], ['ref_tip_openings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_submissions')
    op.drop_table('ref_tip_openings')
    op.drop_table('ref_reeds')
    op.drop_table('ref_mouthpieces')
    # ### end Alembic commands ###
